timesteps: [0,250]

blur_kernel_size: 15
system_g: 3
feature_dim: 256

name: "${exp_setting}_linear-projector-d256_${brain_backbone}_${vision_backbone}"

models:
  brain:
    target: "base.eeg_backbone.${brain_backbone}"
    params:
        c_num: 17
        z_dim: ${z_dim}
        timesteps: ${timesteps}
  eeg_projector:
    target: "main_joint.Projector"
    params:
      input_dim: ${z_dim}
      output_dim: ${feature_dim}
  image_projector:
    target: "main_joint.Projector"
    params:
      input_dim: ${z_dim}
      output_dim: ${feature_dim}

data:
  data_dir: data/things-eeg/Preprocessed_data_250Hz_whiten
  selected_ch: ['P7', 'P5', 'P3', 'P1','Pz', 'P2', 'P4', 'P6', 'P8', 'PO7', 'PO3', 'POz', 'PO4', 'PO8','O1', 'Oz', 'O2']
  model_type: ${vision_backbone}
  train_batch_size: 1024
  val_batch_size: 200
  test_batch_size: 200
  uncertainty_aware: False
  blur_type:
    target: base.inpating_data.UniformBlur
    params:
          blur_kernel_size: ${blur_kernel_size}

  train_avg: True
  test_avg: True
  timesteps: ${timesteps}

train:
  epoch: ${epoch}
  optimizer: AdamW
  lr: ${lr}
  
save_dir: 'exp'